# theme id v16.4.0: 95991300155
# theme id v16.5.3: 95988416571
development:
  password: ${DEV_PASSWD}
  theme_id: ${DEV_THEMEID}
  store: ${DEV_SHOP}
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json

production:
  password: ${PRO_PASSWD}
  theme_id: ${PRO_THEMEID}
  store: ${PRO_SHOP}
  readonly: true
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json
